service_accounts:

  - username: paymentsvc
    uid: 2003
    group: paymentsgroup
    home: /opt/payments 

  - username: ordersvc
    uid: 2004
    group: odersgroup
    home: /opt/orders

  - username: invoicesvc
    uid: 2005
    group: invoicegroup
    home: /opt/invoice
