- name: Create Service Accounts
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    home: "{{ item.home }}"
    shell: /sbin/nologin
    create_home: yes  
  loop: "{{ service_accounts }}"

