---
- name: Checking Disk Use
  hosts: webservers
  become: yes
  tasks: 
    - name: Store Disk use 
      command: 
        cmd: 'df -h | tail -n 1 | awk { print $5 }'
        register: diskUsage
    
    - name: Warning if disk usage is more than 80
      debug:
        msg: " Disk usage is more than 50 "
      when: diskUsage.stdOut | replace ("%", "") | int > 50

