--- 
- name: Install Mariadb pacakage 
  hosts: dbservers
  become: yes
  tasks: 
    - name: install Mariadb 
      yum:
        name: mariadb-server
        state: present

    - name: Enable Service
      service: 
        name: mariadb
        state: started 
        enabled: yes


         
